dist: xenial
language: python
python:
  - 3.6
  - 3.7
notifications:
  email:
    - nick.hand@phila.gov
env:
  global:
    - secure: NwECQbVV0OfPPZGE9eXPGaRwnF/WLL09EKqkMTsOsvIuKhizVaXg7PHHmcrD+cIKyftFJGfNYHL1Ea4RD88HFc4NmZqIfuPwtnzb9Gmr2g2MNpmS0GJKhqjytWlVTcM9JIz2NmQFX6HHW98cCcDp/v/obx9he0GjNAkzIdWHwyeet/5wvhHfNBDRV/cEFWQyNRgFPkq5ARbLC2+FU4u7O8HATBXdglgo98P2iDJI9n+1YUNoijcUNI+F6OKCepqzdf1Ir0559o3+mjfHgiEBLLlf/ozdFux/HWftXE7I5EikBKvotg+AtoWFmV6YFjXWKVTeLkJTFxSStVru84Wksird0tyFpqlE67xXDj/zxbzmqBp34zV6xPsqyb6TtdSG1G9x9ulMn/7mnUKvJ0B+c2x6HiMz4st3gJ9SXXwYZQI56d0VtACWtRDBAtoehIpuOnVsrSm/pOLRgWj4lnzpGSb6s+tjgTHgkGUqjN4ZBVGV6v4EvuzX8GPXQVY/16gXrunKH5aVMKvT+Q0aU8PLqc5WEyCqXzNUxTdzsGvTINdafO61F2MvF0jpiJzlMaAvXLlLX4WjR9x5kiVBjLBKMidY70J41PVmY/3lnUJGYdGt39kxgqmzNGn7LwP0tmMamCadFXg5HIkGa8Jatkybs1nZzmHCQTjvoGJZCj/MWbo=
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.conda"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b -p $HOME/miniconda"
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION conda-build jinja2 anaconda-client
  - conda install -c conda-forge --yes --file requirements.txt
  - pip install .[dev]
script:
  - py.test . --cov carto2gpd
after_success:
  - coveralls
  - chmod +x deploy_anaconda.sh
deploy:
  - provider: pypi
    distributions: sdist
    user: controllerphl
    password:
      secure: keGn0/axREIRCS2bDgUqIH+aScwuoMWAtK3BwTu0avsSAou77/+kgD2sDE1vamP6yqcp1msuIm3SpvzvsowkwsDKEMiMwVbGLCPc5F+pEvkdxwnGgScEpwQNzqiYFzrUbLEthJEk+HeaqihiY2ijk1/iGoV+CqyEbpi09IytbbWl6+lBsTtNTU/HMf34V+ShrW9lN5dJSuMGKmTyUDphrjBx0R2qmlD2RiGHHZBZ4cnaenEH7qVJ2sCfMIeYYY/DM+MmQT70RGwPNj+3tVHk21opvMDxd1RnHnhR3QqJ+xSIfOTtsktJL8U1S3nOdXzJGEoHKGGuRUFMi22hp1cIMkGvao0cuIFTaf5FL2704xRH7UtLnhPPv6CFyXaQPj+VSQuk/35sGaqNmCcSxQBM9L32ClfkOUODPq5UwH+U/VtlOImK+UpgehSiheHV7Rfa+T8CFsgNwvvss1LCHsZoT9ZOMZ7RDzX4y/drafQmdrpEg3uuHLgSgJL2AoDfY9dEGb8u216GANJ4+1nC+hVX/MjJI4wdoX16fKeLKXD6uj8DWMp/eZ4moj0pRh7qE41iWyfEl4BZXwR1tog1PLHSzNRolnJaFHJej8x3nfef1JoXJiBaxU21n3HcV5y6um/qFYQprKCWldyA/7wgr+7CLFwXrVY+sDJOsOVwqmEfjH0=
    skip_existing: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
  - provider: script
    script: "./deploy_anaconda.sh"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
